#!/usr/bin/env python3
"""Bounded, conditional own-farm execution checks, never competitive games.
Only the source prefix before branch_start initializes the policy. Every later
own observation is generated by official unit/market/maintenance functions.
No recorded future observation or rival action is consumed after branching.
"""
from pathlib import Path
import argparse,importlib.util,copy,json,gzip,ctypes,time,hashlib,collections,sys
sys.dont_write_bytecode=True
B=Path(__file__).resolve().parents[1]
OUT=B/'test_runs/own_branches'
def load(path,name):
 s=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
rt=load(B/'evidence/feedback/referee/cpu_runtime.py','r3_own_official');eng=rt.load_engine();A=rt.AttrDict

def own_transition(o,action,clearance=True,supply=0):
 # Rival farm stays at its public current state. It sends no market order;
 # optional exogenous sale supply is a declared public-state stress scenario.
 seat=o['player'];f=o['farms'][seat];private=o['private'];t=o['step'];day=o['day'];logs=[]
 acts=[action.get('farmer',['PASS']),*action.get('hands',[])]
 demand=collections.Counter(a[1] for a in acts if a[0]=='PLANT')
 blocked={crop for crop,n in demand.items() if n>private['seeds'].get(crop,0)}
 for u,a in enumerate(acts):
  if u>=len(private['inventories']):break
  pos=copy.deepcopy(f['farmer'] if u==0 else f['hands'][u-1]);bag=private['inventories'][u];inv0=copy.deepcopy(bag);tile0=copy.deepcopy(f['tiles'][pos[1]][pos[0]]);shed0=copy.deepcopy(private['shed'])
  if a[0]=='PLANT' and a[1] in blocked:a=['PASS']
  eng._apply_unit_action(f,private,u,a,10,day,24,100)
  entry={'step':t,'u':u,'pos':pos,'action':a}
  if a[0] in ('DROP','PLACE'):
   delta={i:private['shed'].get(i,0)-shed0.get(i,0) for i in set(private['shed'])|set(shed0)}
   entry.update(shed_change={i:q for i,q in delta.items() if q},inventory_before=inv0,inventory_after=copy.deepcopy(private['inventories'][u]))
   if a[0]=='DROP':entry['discarded']=sum(inv0.values())-sum(delta.values())
  elif a[0] not in ('PASS','NORTH','SOUTH','EAST','WEST'):
   entry['effect']=tile0!=f['tiles'][pos[1]][pos[0]] or inv0!=private['inventories'][u]
  logs.append(entry)
 before_cash=f['money'];before_shed=copy.deepcopy(private['shed'])
 cfg=A({k:copy.deepcopy(v.get('default') if isinstance(v,dict) else v) for k,v in eng.specification['configuration'].items()});env=A(configuration=cfg)
 public=A(step=t,day=day,hour=o['hour'],farms=o['farms'],market=o['market'],town=o['town'])
 states=[A(observation=A(public),action={'market':[]}) for _ in range(2)]
 states[seat].observation.private=private
 states[1-seat].observation.private={'shed':{},'seeds':{},'inventories':[{}]}
 m=copy.deepcopy(action.get('market',[]))
 if not clearance:m=[q for q in m if q[0]!='SELL']
 states[seat].action={'market':m}
 if supply:
  # Fixed shock is intentionally synthetic, not inferred hidden rival stock.
  for i in ('STRAWBERRY','MELON','MILK','WOOL'):o['market']['inventory'][i]+=supply
  eng._refresh_prices(o['market'])
 eng._process_market(states,env);eng._town_consume(env,states,t);eng._decay_plants(f,t)
 sale_info={'step':t,'orders':m,'cash_change':f['money']-before_cash,'shed_before':before_shed,'shed_after':copy.deepcopy(private['shed'])}
 night=None
 if (t+1)%24==0:
  eng._daily_refresh_plants(f,day,24);eng._daily_refresh_animals(f,day)
  before=sum(private['shed'].values())+sum(sum(b.values()) for b in private['inventories']);shed_before=copy.deepcopy(private['shed']);bags=copy.deepcopy(private['inventories'])
  eng._drop_inventories_to_shed(private,100);night={'lost':before-sum(private['shed'].values()),'shed_before':shed_before,'bags_before':bags,'shed_after':copy.deepcopy(private['shed'])}
 o['step']=t+1;o['day']=(t+1)//24;o['hour']=(t+1)%24
 return logs,sale_info,night

def run(case,start,main,library,label,clearance=True,supply=0):
 tr=json.loads(gzip.decompress((B/'evidence/feedback/own_traces'/f'{case}.json.gz').read_bytes()));mod=load(main,'branch_'+label);agent=mod.create_agent(library)
 get=getattr(agent.lib,'td_delivery_handoff_json',None)
 if get:get.argtypes=[ctypes.c_void_p];get.restype=ctypes.c_char_p
 for t,o in enumerate(tr['observations'][:start]):
  act=agent(copy.deepcopy(o),tr['configuration']);assert act==tr['own_actions'][t],(case,label,'prebranch mismatch',t)
 o=copy.deepcopy(tr['observations'][start]);cash0=o['farms'][o['player']]['money'];frames=[];night=None
 while o['step']//24==start//24:
  action=agent(copy.deepcopy(o),tr['configuration']);tele=json.loads(get(agent.handle)) if get else {}
  units,sales,night=own_transition(o,action,clearance,supply)
  frames.append({'step':o['step']-1,'action':action,'delivery':{k:v for k,v in tele.items() if k!='plans'},'unit_effects':units,'market':sales,'night':night})
 agent.close();out={'case':case,'branch_start':start,'label':label,'native_sha256':hashlib.sha256(Path(library).read_bytes()).hexdigest(),'prefix_calls':start,'generated_own_ticks':len(frames),'new_games':0,'assumptions':{'rival_public_farm_static':True,'rival_private_not_used':True,'rival_market_orders':[],'exogenous_supply_per_tick':supply,'own_sell_orders_enabled':clearance,'unknown_weeds_suppressed_at_endpoint':True},'cash_delta':o['farms'][o['player']]['money']-cash0,'night_loss':night['lost'],'endpoint_farm':o['farms'][o['player']],'endpoint_private':o['private'],'frames':frames}
 path=OUT/f'branch_{case}_{start}_{label}_clear{int(clearance)}_supply{supply}.json.gz';path.write_bytes(gzip.compress(json.dumps(out,separators=(',',':')).encode(),mtime=0));return out

def main():
 global OUT
 ap=argparse.ArgumentParser();ap.add_argument('--supply',type=int,default=0);ap.add_argument('--no-clearance',action='store_true');ap.add_argument('--out-dir',type=Path);a=ap.parse_args();OUT=(a.out_dir or OUT).resolve();OUT.mkdir(parents=True,exist_ok=True);rows=[]
 cases=[('aurax_reactive_v1_1801029924_seat0',460),('submission_56149565_1782098909_seat1',613),('market_smart_v8_290316560_seat0',508),('submission_56149565_447907448_seat0',613)]
 for case,start in cases:
  old=run(case,start,B/'parent/main.py',B/'parent/policy/tri_a08_r11_r2_fix1.so','parent',not a.no_clearance,a.supply)
  new=run(case,start,B/'main.py',B/'policy/tri_a08_r11_r3.so','candidate',not a.no_clearance,a.supply)
  # Maintenance and production endpoints are compared, not just a warehouse KPI.
  row={'case':case,'start':start,'ticks_per_branch':old['generated_own_ticks'],'parent_cash_delta':old['cash_delta'],'candidate_cash_delta':new['cash_delta'],'cash_delta_difference':new['cash_delta']-old['cash_delta'],'parent_night_loss':old['night_loss'],'candidate_night_loss':new['night_loss'],'same_endpoint_tiles':old['endpoint_farm']['tiles']==new['endpoint_farm']['tiles'],'same_endpoint_seeds':old['endpoint_private']['seeds']==new['endpoint_private']['seeds'],'new_games':0,'clearance':not a.no_clearance,'supply':a.supply}
  rows.append(row);print(json.dumps(row),flush=True)
 (OUT/f'own_branch_summary_clear{int(not a.no_clearance)}_supply{a.supply}.json').write_text(json.dumps(rows,indent=2))
if __name__=='__main__':main()
