from __future__ import annotations

from src.agent import Agent


# ============================================================
# KAGGRICULTURE AI AGENT
# ============================================================

_agent = Agent()


def agent(obs, config=None):
    """
    Kaggriculture AI Agent entry point.

    Parameters
    ----------
    obs : dict
        Current Kaggriculture game observation.

    config : optional
        Kaggle environment configuration.

    Returns
    -------
    dict
        Action generated by the Kaggriculture agent.
    """

    return _agent.act(obs)
