"""Preserve causal observations and raw actions from every eligible replay seat.

Only engine 1.32.7, terminal 720-frame games are eligible. No holdouts or
winner filtering. Exact worker/market labels are generated by cache_exact.py.
"""
import argparse,gzip,hashlib,json,zipfile
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
from collections import Counter

def convert(job):
    archive,member,output=job;out=Path(output)
    with zipfile.ZipFile(archive) as z:raw=z.read(member)
    replay=json.loads(raw)
    if replay.get('module_version')!='1.32.7':return {'excluded':'engine_version'}
    if replay.get('statuses')!=['DONE','DONE'] or len(replay.get('steps',[]))!=720:return {'excluded':'incomplete'}
    episode=replay.get('info',{}).get('EpisodeId',replay.get('id',Path(member).stem))
    episode=int(episode);steps=replay['steps'];sha=hashlib.sha256(raw).hexdigest()
    receipt=out/'games'/f'{episode}.json'
    if receipt.exists():
        old=json.loads(receipt.read_text())
        if old['raw_sha256']!=sha:raise ValueError(f'Conflicting replay {episode}')
        if all(Path(f).exists() for f in old['files']):return old
    cash=[steps[-1][s]['reward'] for s in (0,1)]
    if any(v is None for v in cash):raise ValueError('Missing terminal rewards')
    row=dict(schema='macro-bc-v2',engine='1.32.7',episode=episode,split='train',
        seed=replay.get('info',{}).get('seed',replay.get('configuration',{}).get('seed')),
        date=Path(archive).parent.name,source=str(Path(archive).resolve())+':'+member,
        raw_sha256=sha,terminal_cash=cash,outcomes=[1 if cash[0]==cash[1] else 2 if cash[s]>cash[1-s] else 0 for s in (0,1)],files=[])
    for seat in (0,1):
        path=out/'trajectories'/f'{episode}-seat{seat}.jsonl.gz';tmp=path.with_suffix('.tmp')
        with gzip.open(tmp,'wt',compresslevel=1) as f:
            for t in range(719):
                obs=dict(steps[t][seat]['observation']);obs.pop('remainingOverageTime',None)
                obs['step']=obs.get('step',steps[t][0]['observation'].get('step'))
                if obs['step']!=t or obs['player']!=seat:raise ValueError('Seat/clock mismatch')
                action=steps[t+1][seat].get('action') or {}
                if not isinstance(action,dict):action={}
                market=action.get('market',[])
                if not isinstance(market,list):market=[]
                record=dict(schema='macro-bc-v2',episode=episode,seat=seat,input_frame=t,action_frame=t+1,
                    observation=obs,raw_worker_action=dict(farmer=action.get('farmer'),hands=action.get('hands',[])),
                    targets=dict(market=[dict(position=i,raw=x) for i,x in enumerate(market[:10])]))
                f.write(json.dumps(record,separators=(',',':'))+'\n')
        tmp.replace(path);row['files'].append(str(path.resolve()))
    receipt.write_text(json.dumps(row,indent=2));return row

def main():
    p=argparse.ArgumentParser();p.add_argument('--downloads',type=Path,required=True)
    p.add_argument('--output',type=Path,required=True);p.add_argument('--workers',type=int,default=32)
    a=p.parse_args();a.output=a.output.resolve()
    for sub in ['games','trajectories']:(a.output/sub).mkdir(parents=True,exist_ok=True)
    jobs=[];seen={};duplicates=0
    for archive in sorted(a.downloads.rglob('kaggriculture-episodes-*.zip')):
        with zipfile.ZipFile(archive) as z:
            for member in sorted(n for n in z.namelist() if n.endswith('.json')):
                key=Path(member).stem
                if key in seen:
                    old_archive,old_member=seen[key]
                    with zipfile.ZipFile(old_archive) as old:
                        if hashlib.sha256(old.read(old_member)).digest()!=hashlib.sha256(z.read(member)).digest():raise ValueError('Conflicting duplicate '+key)
                    duplicates+=1;continue
                seen[key]=(archive,member);jobs.append((str(archive.resolve()),member,str(a.output)))
    if not jobs:raise ValueError('No replay ZIPs found')
    counts=Counter();rows=[]
    with ProcessPoolExecutor(max_workers=a.workers) as pool:
        for i,r in enumerate(pool.map(convert,jobs,chunksize=1),1):
            if 'excluded' in r:counts[r['excluded']]+=1
            else:rows.append(r)
            if i%20==0 or i==len(jobs):
                status=dict(complete=False,scanned=i,total=len(jobs),games=len(rows),excluded=dict(counts),duplicates=duplicates)
                tmp=a.output/'prepare-status.tmp';tmp.write_text(json.dumps(status));tmp.replace(a.output/'prepare-status.json')
                print(json.dumps(status),flush=True)
    if not rows:raise ValueError('No current-engine full games')
    if len({r['episode'] for r in rows})!=len(rows):raise ValueError('Duplicate episode identity')
    (a.output/'manifest.jsonl').write_text(''.join(json.dumps(r)+'\n' for r in sorted(rows,key=lambda r:r['episode'])))
    status.update(complete=True,seat_trajectories=2*len(rows),turns=1438*len(rows),all_replays=True)
    (a.output/'prepare-status.json').write_text(json.dumps(status,indent=2))

if __name__=='__main__':main()
