// Synthetic executable-delivery invariants. No seed or opponent is an input.
#include "../fix1_checks.cpp"
#include <iostream>
namespace r4test {
using namespace dp7;
int assertions=0;std::vector<std::string> rows;
void check(bool v,const char*s){assertions++;if(!v)throw std::runtime_error(s);}
struct Fixture {
 Farm own,opp;PrivateState pr;Market market;std::vector<int8_t>shops;int step=710;
 Fixture(int n=1){own.tiles.resize(100);opp.tiles.resize(100);own.unlocked_mask=opp.unlocked_mask=15;own.money=1000;own.farmer=opp.farmer={4,4};own.hands.resize(n-1,{4,4});pr.inventories.resize(n);pr.inventory_order.resize(n);market.inventory.fill(10000);for(int i=0;i<9;i++)market.prices[i]=price(i,10000);}
 View view()const{return {step,step/24,step%24,own,opp,pr,market,shops};}
 void bag(int u,int i,int q){pr.inventories[u][i]=q;pr.inventory_order[u].clear();for(int k=0;k<12;k++)if(pr.inventories[u][k])pr.inventory_order[u].push_back(k);}
 void crop(int pos,int kind=T,int yield=4){auto&t=own.tiles[pos];t={};t.kind=TileKind::PLANT;t.crop=Item(kind);t.planted_day=10;t.yield_units=yield;t.watered_today=true;t.max_lifespan_step=2000;}
 void animal_at(int pos,int kind=CO){auto&t=own.tiles[pos];t={};t.kind=TileKind::ANIMAL;t.animal=Item(kind);t.placed_day=0;t.yield_units=0;t.fed_today=false;t.cared_today=false;}
 Controller controller()const{Controller c;c.phase=3;c.day=step/24;c.last_step=step-1;c.plans.resize(pr.inventories.size());c.p.stepwise_recoordination=true;c.p.fix_logistics=true;c.p.terminal_deposit_schedule=true;c.p.sell_deposits=true;c.p.action_shadow=2;c.p.shed_safety=1;c.p.max_hands=own.hands.size();return c;}
};
Job harvest(int pos){Job j;j.pos=pos;j.actions={action(Op::HARVEST)};return j;}
void row(std::string name,bool accepted,double delta,int length){std::ostringstream j;j<<"{\"name\":\""<<name<<"\",\"accepted\":"<<accepted<<",\"conditional_cash_delta\":"<<delta<<",\"route_length\":"<<length<<",\"pass\":true}";rows.push_back(j.str());}
void run(){
 for(int step:{710,714,715,716,717,718}){
  Fixture f;f.step=step;f.crop(43);f.bag(0,MI,3);auto o=f.view();auto c=f.controller();auto base=c.plans;base[0]=delivery::rebuild(o,0,{{action(Op::DROP),44}});auto before=delivery::evaluate(c,o,base);auto next=base;bool ok=delivery::terminal_add(c,o,next,harvest(43),719-step);check(ok==(step<=715),"terminal admits incomplete return or rejects reachable sale");
  if(ok){auto after=delivery::evaluate(c,o,next);check(after.cash>before.cash,"accepted terminal plan has no realized cash");check(after.remaining[T]==0,"accepted terminal harvest still in bag");check(next[0].a.back().op==Op::DROP,"terminal return not appended or reused");check(delivery::deadline(o,next),"terminal exceeds last action718");check(delivery::preserves(before,after),"existing delivered cargo lost");row("horizon_"+std::to_string(step),ok,after.cash-before.cash,next[0].a.size());}else{check(Controller::same_remaining(base[0],next[0]),"rejected terminal mutated plan");row("horizon_"+std::to_string(step),false,0,base[0].a.size());}
 }
 // Existing DROP followed by new output is precisely the shared failure shape.
 {Fixture f;f.crop(43);f.bag(0,MI,3);auto o=f.view();auto c=f.controller();c.target={{43,T}};c.plans[0]=delivery::rebuild(o,0,{{action(Op::DROP),44}});auto before=delivery::evaluate(c,o,c.plans);c.recoordinate(o);check(c.delivery_terminal_added>0,"real recoordinate bypassed terminal delivery guard");auto after=delivery::evaluate(c,o,c.plans);check(after.cash>before.cash&&after.remaining[T]==0,"real recoordinate left collected output unsold");row("actual_recoordinate",true,after.cash-before.cash,c.plans[0].a.size());}
 // A positive-looking unit price alone cannot pay the opportunity cost.
 {Fixture f;f.crop(43);auto c=f.controller();c.p.action_shadow=1e8;auto base=c.plans;bool ok=delivery::terminal_add(c,f.view(),base,harvest(43),9);check(!ok,"ignored displaced action opportunity cost");row("shadow_cost_reject",false,0,0);}
 {Fixture f;f.crop(43,T,0);auto c=f.controller();auto base=c.plans;check(!delivery::terminal_add(c,f.view(),base,harvest(43),9),"zero-output job accepted as cash");row("zero_yield_reject",false,0,0);}
 {Fixture f;f.crop(43);f.own.tiles[43].max_lifespan_step=f.step+1;auto c=f.controller();auto base=c.plans;check(!delivery::terminal_add(c,f.view(),base,harvest(43),9),"expired harvest admitted");row("expiry_reject",false,0,0);}
 // Prerequisite order is global across workers, not just inside each route.
 {Fixture f(2);f.crop(43,W);f.own.tiles[43].watered_today=false;auto o=f.view();std::vector<Plan>ps(2);ps[0]=delivery::rebuild(o,0,{{action(Op::HARVEST),43}});ps[1]=delivery::rebuild(o,1,{{action(Op::WATER),43}});check(!delivery::new_precedence(o,ps,harvest(43)),"harvest reordered before finite watering");ps[0]=delivery::rebuild(o,0,{{action(Op::WATER),43},{action(Op::HARVEST),43},{action(Op::DROP),44}});ps[1]={};check(delivery::new_precedence(o,ps,harvest(43)),"valid finite crop chain rejected");auto c=f.controller();auto e=delivery::evaluate(c,o,ps);check(e.valid&&e.cash>o.own.money,"finite harvest-water-deliver chain not executable");row("finite_precedence",true,e.cash-o.own.money,ps[0].a.size());}
 // Capacity and same-tick unit/market order are part of terminal acceptance.
 for(int n:{0,95,100}){Fixture f(2);f.step=715;f.crop(43,T,4);f.pr.shed[W]=n;f.bag(1,MI,5);auto o=f.view();auto c=f.controller();auto ps=c.plans;ps[1]=delivery::rebuild(o,1,{{action(Op::DROP),44}});auto before=delivery::evaluate(c,o,ps);bool ok=delivery::terminal_add(c,o,ps,harvest(43),4);check(ok,"available later shed capacity not exploited");auto after=delivery::evaluate(c,o,ps);check(after.overflow==0&&delivery::preserves(before,after),"terminal capacity dropped committed stock");check(after.cash>before.cash,"terminal capacity accepted without actual sale");row("warehouse_"+std::to_string(n),ok,after.cash-before.cash,delivery::steps(ps));}
 // Product PLACE is legal only at depot, and retains material for planned care.
 {Fixture f;f.step=480+12;f.bag(0,MI,30);f.bag(0,W,1);f.bag(0,F,2);f.animal_at(34);auto o=f.view();auto c=f.controller();Action a=action(Op::PLACE,MI,30);check(c.semantic_needed(o,0,a,44),"selective product deposit considered stale");check(!c.semantic_needed(o,0,a,34),"off-depot product drop allowed");auto ps=c.plans;ps[0]=delivery::rebuild(o,0,{{a,44},{action(Op::FEED),34},{action(Op::CARE),34}});auto e=delivery::evaluate(c,o,ps);check(e.valid&&e.deposited>=30,"selective PLACE did not deposit");check(e.effects[{34,int(Op::FEED),int(Item::NONE)}]==1,"selective PLACE consumed reserved feed");check(e.effects[{34,int(Op::CARE),int(Item::NONE)}]==1,"selective PLACE displaced care");check(e.remaining[F]==2,"selective PLACE lost unused fertilizer");row("selective_input_retention",true,e.cash-o.own.money,ps[0].a.size());}
 // Free service handoff / direct wave cannot remove already paid field work.
 for(bool pressure:{false,true}){
  Fixture f(2);f.step=492;f.bag(0,MI,pressure?60:10);f.bag(0,W,1);f.bag(0,F,1);f.bag(1,WO,pressure?70:10);f.crop(4,T,0);f.own.tiles[4].watered_today=false;f.animal_at(99);auto o=f.view();auto c=f.controller();c.p.midroute_delivery=true;c.plans[0]=delivery::rebuild(o,0,{{action(Op::WATER),4}});c.plans[1]=delivery::rebuild(o,1,{{action(Op::CARE),99}});auto before=delivery::evaluate(c,o,c.plans);auto old=c.plans;bool ok=delivery::overflow_wave(c,o);check(ok==pressure,"overflow wave pressure test wrong");if(ok){auto after=delivery::evaluate(c,o,c.plans);check(delivery::preserves(before,after),"haul lost successful maintenance");check(after.overflow<before.overflow,"haul did not free capacity");check(after.deposited>before.deposited,"haul remained an intention only");check(c.delivery_added_steps>=0,"unexpected test step delta");check(c.plans.size()==2,"wave hires speculative worker");row("overflow_positive",true,after.cash-before.cash,delivery::steps(c.plans));}else{check(Controller::same_remaining(c.plans[0],old[0])&&Controller::same_remaining(c.plans[1],old[1]),"no-pressure plan changed");row("overflow_negative",false,0,delivery::steps(old));}
 }
 {Fixture f(2);f.step=502;f.bag(0,MI,70);f.bag(1,WO,70);auto c=f.controller();auto old=c.plans;check(!delivery::overflow_wave(c,f.view()),"late automatic deposit counted as safe wave");row("too_late_wave",false,0,0);}
 // No finite-resource action is eligible for transfer or terminal no-input job.
 for(Op op:{Op::FEED,Op::FERTILIZE,Op::PICKUP,Op::PLANT,Op::BUY_PRODUCT}){Job j;j.pos=43;j.actions={action(op,W)};check(!Controller::resource_free_service(j),"material action classified as free");}
 // Fixed reevaluation must leave the incoming controller/callback state intact.
 {Fixture f;f.crop(43);auto c=f.controller();c.pending_admission={true,29,710,0,43,T};c.queue.push_back(action(Op::BUY_PRODUCT,W,5));auto ps=c.plans;ps[0]=delivery::rebuild(f.view(),0,{{action(Op::HARVEST),43},{action(Op::DROP),44}});auto before=c;auto e=delivery::evaluate(c,f.view(),ps);check(e.valid&&c.pending_admission.active&&c.queue.size()==1,"evaluation mutates incoming procurement/commitment");check(c.plans.size()==before.plans.size()&&c.phase==before.phase&&c.last_step==before.last_step,"evaluation advances live controller");row("evaluation_isolation",true,e.cash-f.own.money,ps[0].a.size());}
}
}
int main(){try{r4test::run();std::cout<<"{\"pass\":true,\"assertions\":"<<r4test::assertions<<",\"scenarios\":"<<r4test::rows.size()<<",\"new_games\":0,\"results\":[";for(size_t i=0;i<r4test::rows.size();i++){if(i)std::cout<<",";std::cout<<r4test::rows[i];}std::cout<<"]}\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<r4test::assertions<<" assertions: "<<e.what()<<"\n";return 1;}}
