#!/usr/bin/env python3
"""Pack the full replay+R1 agent (agent/ + policy/r1/ + meta_agent/) into one .py.

Kaggle code competitions take a single file whose module exposes
``agent(observation, configuration)``.  Our agent is a small tree of files plus a
compiled x86_64 R1 extension, so the payload materialises that tree into a temp
directory at import time and execs the real ``agent/main.py`` from there -- this
keeps every relative path in the original code untouched.

The extension is passed in explicitly: the local build here is aarch64, so the
Kaggle payload needs an x86_64 build (see --so).
"""
from __future__ import annotations
import argparse, base64, hashlib, json, zlib
from pathlib import Path

TEXT = ["agent/main.py", "agent/teammate_base.py", "agent/route_library.json",
        "agent/route_policy.json", "agent/replay_deployment.json",
        "policy/r1/agent.py", "policy/r1/config.json",
        "meta_agent/__init__.py", "meta_agent/src/__init__.py",
        "meta_agent/src/route_switch_features.py",
        "meta_agent/src/search_route_policy.py",
        "meta_agent/src/teammate_expanded_routes.py",
        "meta_agent/src/market_manager.py"]
BINARY = ["agent/route_actions.json.zlib"]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--so", type=Path, required=True, help="x86_64 policy/r1/agent.so")
    ap.add_argument("--output", type=Path, default=Path("build/kaggriculture_submission.py"))
    a = ap.parse_args()
    root = a.root.resolve()

    files = {}
    for rel in TEXT:
        files[rel] = (root / rel).read_bytes()
    for rel in BINARY:
        files[rel] = (root / rel).read_bytes()
    files["policy/r1/agent.so"] = a.so.read_bytes()

    payload = {rel: base64.b85encode(zlib.compress(b, 9)).decode() for rel, b in files.items()}
    body = (
        "# Single-file Kaggriculture submission (replay route tree -> warm R1).\n"
        "# Unpack: zlib + Base85 per file.  Generated by scripts/pack_kaggle_submission.py.\n"
        "import base64 as _b, zlib as _z, pathlib as _p, sys as _s, tempfile as _t, os as _o\n"
        "_FILES = " + repr(payload) + "\n"
        "_root = _t.mkdtemp(prefix='kagg_subm_')\n"
        "for _rel, _blob in _FILES.items():\n"
        "    _dst = _p.Path(_root) / _rel\n"
        "    _dst.parent.mkdir(parents=True, exist_ok=True)\n"
        "    _dst.write_bytes(_z.decompress(_b.b85decode(_blob)))\n"
        "_o.chmod(_p.Path(_root) / 'policy/r1/agent.so', 0o755)\n"
        "_s.path.insert(0, _root)\n"
        "_entry = _p.Path(_root) / 'agent/main.py'\n"
        "_ns = {'__file__': str(_entry), '__name__': '_kaggriculture_submission'}\n"
        "exec(compile(_entry.read_text(encoding='utf-8'), str(_entry), 'exec'), _ns)\n"
        "agent = _ns['agent']\n"
    )
    a.output.parent.mkdir(parents=True, exist_ok=True)
    a.output.write_text(body, encoding="utf-8")
    print(json.dumps({
        "output": str(a.output.resolve()),
        "files": len(files),
        "so_bytes": len(files["policy/r1/agent.so"]),
        "file_bytes": a.output.stat().st_size,
        "sha256": hashlib.sha256(a.output.read_bytes()).hexdigest(),
    }, indent=2))


if __name__ == "__main__":
    main()
