"""Train a small public-feature VALUE correction, not an action/tape predictor.
The only training inputs are the frozen feature matrix. Labels may use complete
offline simulator outcomes. Seed/opponent identity are excluded from X.
"""
from pathlib import Path
import numpy as np,json,hashlib,argparse
import lightgbm as lgb
from sklearn.metrics import mean_squared_error
R=Path(__file__).resolve().parent
p=argparse.ArgumentParser();p.add_argument('--data',default='train16');p.add_argument('--name',default='value_v1');p.add_argument('--leaves',type=int,default=15);p.add_argument('--min-leaf',type=int,default=35);p.add_argument('--trees',type=int,default=400);a=p.parse_args()
d=R/'labels'/a.data;out=R/'models'/a.name;out.mkdir(exist_ok=False,parents=True)
rows=json.loads((d/'labels.json').read_text());X=np.load(d/'features.npz')['X'];schema=json.loads((R/'tests/feature_schema.json').read_text());assert len(schema)==X.shape[1]
m=np.array([r['margin'] for r in rows]);ref=np.array([r['reference_cash']-r['reference_opponent_cash'] for r in rows])
# Smooth win utility, with a small margin term: never optimize the seven labels
# through an opponent identity feature or hard-coded opponent route switch.
def utility(z):return .8*np.tanh(z/10000)+.2*np.clip(z/60000,-2,2)
y=utility(m)-utility(ref)
ids=np.array([r['candidate'] for r in rows]);seeds=np.array([r['seed'] for r in rows]);unique=sorted(map(int,set(seeds)));cut=unique[max(1,len(unique)*3//4)]
train=(seeds<cut)&(ids!=0);valid=(seeds>=cut)&(ids!=0)
params=dict(objective='regression',learning_rate=.035,num_leaves=a.leaves,min_child_samples=a.min_leaf,n_estimators=a.trees,reg_lambda=5.,colsample_bytree=.9,subsample=1.,random_state=260908,n_jobs=4,verbosity=-1,force_col_wise=True)
model=lgb.LGBMRegressor(**params)
model.fit(X[train],y[train],eval_set=[(X[valid],y[valid])],callbacks=[lgb.early_stopping(40,verbose=False)])
best=int(model.best_iteration_ or a.trees);pred=model.predict(X);pred[ids==0]=0
buckets={}
for i,r in enumerate(rows):buckets.setdefault((r['seed'],r['opponent'],r['seat'],r['day']),[]).append(i)

def quality(mask):
 gs=[g for g in buckets.values() if mask[g[0]] and len(g)>1]
 def selected(score):return [max(g,key=lambda i:score[i]) for g in gs]
 keep=[g[0] for g in gs];sel=selected(pred);oracle=selected(y)
 return dict(groups=len(gs),keep_win=float(np.mean(m[keep]>0)),selected_win=float(np.mean(m[sel]>0)),oracle_win=float(np.mean(m[oracle]>0)),mean_utility_gain=float(y[sel].mean()),oracle_utility_gain=float(y[oracle].mean()),mean_cash_margin_gain=float((m[sel]-ref[sel]).mean()),choice_changes=int(sum(ids[sel]!=0)))
report=dict(data=a.data,rows=len(rows),features=X.shape[1],train_seeds=unique[:unique.index(cut)],validation_seeds=unique[unique.index(cut):],best_iteration=best,validation_mse=float(mean_squared_error(y[valid],pred[valid])),train=quality(seeds<cut),validation=quality(seeds>=cut),params=params,online_policy_test_required=True)
# Freeze number of trees from group-held validation, then use all label seeds.
params['n_estimators']=best
final=lgb.LGBMRegressor(**params).fit(X[ids!=0],y[ids!=0]);final.booster_.save_model(str(out/'model.txt'))
dump=final.booster_.dump_model();(out/'model.json').write_text(json.dumps(dump,separators=(',',':')))
(out/'feature_schema.json').write_text(json.dumps(schema,indent=2));(out/'training_report.json').write_text(json.dumps(report,indent=2));np.savez_compressed(out/'prediction_fixture.npz',X=X[::max(1,len(X)//256)],pred=final.predict(X[::max(1,len(X)//256)]))
# Export numerical trees. Leaves already include the boosting shrinkage.
nodes=[];roots=[]
def visit(t):
 index=len(nodes);nodes.append(None)
 if 'leaf_value' in t:nodes[index]=(-1,-1,-1,float(t['leaf_value']))
 else:
  assert t['decision_type']=='<=' and not isinstance(t['threshold'],str)
  l=visit(t['left_child']);r=visit(t['right_child']);nodes[index]=(int(t['split_feature']),l,r,float(t['threshold']))
 return index
for tree in dump['tree_info']:roots.append(visit(tree['tree_structure']))
text='''#pragma once
// Generated by train_value.py from offline paired counterfactual labels.
// Inputs are public-observation features; no seed, opponent ID or future.
#include <vector>
namespace triad::learned {
inline constexpr bool available=true;
struct Node {int feature,left,right;double value;};
inline constexpr Node nodes[]={\n'''
text+='\n'.join('{%d,%d,%d,%.17g},'%v for v in nodes)
text+='\n};\ninline constexpr int roots[]={'+','.join(map(str,roots))+'};\n'
text+='inline double predict(const std::vector<double>&x){if(x.size()!='+str(X.shape[1])+')return 0.;double sum=0;for(int root:roots){int i=root;while(nodes[i].feature>=0){const auto&n=nodes[i];i=x[n.feature]<=n.value?n.left:n.right;}sum+=nodes[i].value;}return sum;}\ninline double score(const std::vector<double>&x,bool keep){return keep?0.:predict(x); }\n}\n'
(out/'learned_value.hpp').write_text(text);(R/'policy/learned_value.hpp').write_text(text)
report['model_sha256']=hashlib.sha256((out/'model.txt').read_bytes()).hexdigest();report['header_sha256']=hashlib.sha256(text.encode()).hexdigest();(out/'training_report.json').write_text(json.dumps(report,indent=2));print(json.dumps(report),flush=True)
