"""Pairwise public-feature candidate ranker; KEEP participates in each group."""
from pathlib import Path
import numpy as np,json,argparse,hashlib
import lightgbm as lgb
R=Path(__file__).resolve().parent
p=argparse.ArgumentParser();p.add_argument('--name',default='rank_v1');a=p.parse_args();out=R/'models'/a.name;out.mkdir(exist_ok=False,parents=True)
d=R/'labels/train16';rows=json.loads((d/'labels.json').read_text());X=np.load(d/'features.npz')['X'];schema=json.loads((R/'tests/feature_schema.json').read_text())
m=np.array([r['margin'] for r in rows]);ref=np.array([r['reference_cash']-r['reference_opponent_cash'] for r in rows]);seed=np.array([r['seed'] for r in rows]);ids=np.array([r['candidate'] for r in rows])
u=lambda z:.8*np.tanh(z/10000)+.2*np.clip(z/60000,-2,2)
gain=u(m)-u(ref)
relevance=np.digitize(gain,[-.3,-.06,-.005,.005,.06,.3]).astype(int)
groups=[];last=None
for i,r in enumerate(rows):
 key=(r['seed'],r['seat'],r['opponent'],r['day'])
 if key!=last:groups.append([]);last=key
 groups[-1].append(i)
tr=[g for g in groups if seed[g[0]]<260908144];va=[g for g in groups if seed[g[0]]>=260908144]
ti=np.concatenate(tr);vi=np.concatenate(va)
params=dict(objective='lambdarank',label_gain=list(range(7)),metric='ndcg',learning_rate=.04,n_estimators=300,num_leaves=15,min_child_samples=35,reg_lambda=8,random_state=260908,n_jobs=3,verbosity=-1,force_col_wise=True)
mod=lgb.LGBMRanker(**params).fit(X[ti],relevance[ti],group=list(map(len,tr)),eval_set=[(X[vi],relevance[vi])],eval_group=[list(map(len,va))],eval_at=[1],callbacks=[lgb.early_stopping(35,verbose=False)])
best=mod.best_iteration_;pred=mod.predict(X)
def quality(gs):
 gs=[g for g in gs if len(g)>1];sel=np.array([max(g,key=lambda i:pred[i]) for g in gs]);keep=np.array([g[0] for g in gs]);oracle=np.array([max(g,key=lambda i:m[i]) for g in gs])
 return dict(groups=len(gs),keep_win=float(np.mean(m[keep]>0)),selected_win=float(np.mean(m[sel]>0)),oracle_win=float(np.mean(m[oracle]>0)),selected_utility_gain=float(gain[sel].mean()),changes=int(np.sum(ids[sel]!=0)))
report=dict(method='lambdarank; KEEP included; relative utility bins with linear gains',data='train16',best_iteration=int(best),train=quality(tr),validation=quality(va),features=X.shape[1],online_policy_test_required=True)
params['n_estimators']=int(best);final=lgb.LGBMRanker(**params).fit(X,relevance,group=list(map(len,groups)));final.booster_.save_model(str(out/'model.txt'))
dump=final.booster_.dump_model();(out/'model.json').write_text(json.dumps(dump,separators=(',',':')));nodes=[];roots=[]
def visit(t):
 i=len(nodes);nodes.append(None)
 if 'leaf_value' in t:nodes[i]=(-1,-1,-1,float(t['leaf_value']))
 else:
  assert t['decision_type']=='<=' and not isinstance(t['threshold'],str)
  l=visit(t['left_child']);r=visit(t['right_child']);nodes[i]=(int(t['split_feature']),l,r,float(t['threshold']))
 return i
for t in dump['tree_info']:roots.append(visit(t['tree_structure']))
text='#pragma once\n// Offline public-feature pairwise value ranker, generated by train_ranker.py.\n#include <vector>\nnamespace triad::learned {\ninline constexpr bool available=true;\nstruct Node{int feature,left,right;double value;};\ninline constexpr Node nodes[]={\n'+'\n'.join('{%d,%d,%d,%.17g},'%v for v in nodes)+'\n};\ninline constexpr int roots[]={'+','.join(map(str,roots))+'};\n'
text+='inline double predict(const std::vector<double>&x){if(x.size()!='+str(X.shape[1])+')return 0;double sum=0;for(int root:roots){int i=root;while(nodes[i].feature>=0){const auto&n=nodes[i];i=x[n.feature]<=n.value?n.left:n.right;}sum+=nodes[i].value;}return sum;}\ninline double score(const std::vector<double>&x,bool keep){return predict(x);}\n}\n'
(out/'learned_value.hpp').write_text(text);(R/'policy/learned_value.hpp').write_text(text);report['model_sha256']=hashlib.sha256((out/'model.txt').read_bytes()).hexdigest();(out/'training_report.json').write_text(json.dumps(report,indent=2));(out/'feature_schema.json').write_text(json.dumps(schema))
xx=X[::max(1,len(X)//256)];np.savez_compressed(out/'prediction_fixture.npz',X=xx,pred=final.predict(xx));print(json.dumps(report),flush=True)
# Install scorer interface only after actual model export.
s=R/'policy/search.hpp';text=s.read_text().replace('proposal.id==0||!learned::available?0:learned::predict(proposal.features.x)','!learned::available?0:learned::score(proposal.features.x,proposal.id==0)');s.write_text(text)
