#pragma once
// Generated by train_value.py from offline paired counterfactual labels.
// Inputs are public-observation features; no seed, opponent ID or future.
#include <vector>
namespace triad::learned {
inline constexpr bool available=true;
struct Node {int feature,left,right;double value;};
inline constexpr Node nodes[]={
{323,1,18,12.000000000000002},
{152,2,17,160.00000000000003},
{355,3,14,25.500000000000004},
{80,4,9,1.0000000180025095e-35},
{2,5,8,424.50000000000006},
{50,6,7,4.5000000000000009},
{-1,-1,-1,-0.022330272924315615},
{-1,-1,-1,-0.011155610211055994},
{-1,-1,-1,-0.022755542503253366},
{8,10,13,1.5000000000000002},
{339,11,12,-8.4999999999999982},
{-1,-1,-1,-0.029244064651088},
{-1,-1,-1,-0.023426117497284151},
{-1,-1,-1,-0.031647965942327556},
{12,15,16,1.0000000180025095e-35},
{-1,-1,-1,-0.021460622573581101},
{-1,-1,-1,-0.014600210140549828},
{-1,-1,-1,-0.013731415937226481},
{209,19,26,2.5000000000000004},
{221,20,21,-1.0000000180025095e-35},
{-1,-1,-1,-0.01984668970800544},
{288,22,23,15.000000000000002},
{-1,-1,-1,-0.024226166964095078},
{71,24,25,28.500000000000004},
{-1,-1,-1,-0.033542571117438552},
{-1,-1,-1,-0.024528368130489444},
{192,27,28,1.5000000000000002},
{-1,-1,-1,-0.037320476182567848},
{-1,-1,-1,-0.024971247621538541},
};
inline constexpr int roots[]={0};
inline double predict(const std::vector<double>&x){if(x.size()!=356)return 0.;double sum=0;for(int root:roots){int i=root;while(nodes[i].feature>=0){const auto&n=nodes[i];i=x[n.feature]<=n.value?n.left:n.right;}sum+=nodes[i].value;}return sum;}
}
