from pathlib import Path
import json,hashlib
r=Path('/mnt/data/fix1_work'); orig=r/'original_r2'; out=r/'repro'
s=(orig/'policy/animal_service_dp.hpp').read_text(); body=s[s.index('struct AnimalServiceDP'):s.index(' Choice first(')]+ '};\n'
pre='''// Standalone reduction of the ORIGINAL delivered r2 recurrence.\n// No game engine, simulator, trace, foreign memory or private opponent data.\n// GCC13 failure was reported centrally; local compiler matrix is logged.\n#include <array>\n#include <algorithm>\n#include <cstdio>\n#ifndef A08_ANIMAL_COLLECTION_LABOR\n#define A08_ANIMAL_COLLECTION_LABOR 1\n#endif\nconstexpr int W=0,E=5,F=8;\nconstexpr std::array<int,3> afirst{4,8,6}, ainterval{1,2,3}, held{4,6,6}, product{5,6,7};\nusing Flow=std::array<std::array<double,9>,30>;\n'''
post='''int main() {\n Flow prices{};for(auto &d:prices){d.fill(30.);d[W]=25.;d[F]=2.;}\n AnimalServiceDP poor;poor.solve(9,21,28,prices,4.);\n for(auto &d:prices)d[E]=100.;\n AnimalServiceDP rich;rich.solve(9,21,28,prices,4.);\n auto q=rich.choices[28][1][0];\n std::printf("poor.feed=%d poor.value=%.17g rich.feed=%d rich.care=%d rich.choice_value=%.17g rich.value=%.17g terminal=%.17g\\n",poor.choices[28][1][0].feed,poor.value[28][1][0],q.feed,q.care,q.value,rich.value[28][1][0],rich.value[29][0][0]);\n return !(poor.choices[28][1][0].feed==0 && poor.value[28][1][0]==0 && q.feed==1 && q.care==0 && q.value==65 && rich.value[28][1][0]==65 && rich.value[29][0][0]==0);\n}\n'''
(out/'original_standalone.cpp').write_text(pre+body+post)
(out/'original_standalone_boundary.cpp').write_text(pre+body.replace(' void solve(','''\n#if defined(__GNUC__) && !defined(__clang__)\n __attribute__((noipa))\n#elif defined(__clang__)\n __attribute__((noinline))\n#endif\n void solve(''')+post)
# Direct production-header case retains the original constants/call syntax.
(out/'direct_header.cpp').write_text('#include "policy/animal_service_dp.hpp"\n#include <cstdio>\nusing namespace competitive;\n'+post)
(r/'source_review.txt').write_text('''Original recurrence bounds reviewed: kind 9..11 -> j 0..2; h 0..1; p 0..held[j]-1 <=5; day d<=28; nh checked before indexing; np capped at held[j]-1; terminal values are aggregate-zero initialized. The reduced reproducer uses only these bounds and no engine. No source UB has been established. A compiler issue is NOT claimed proven without local GCC13 reproduction. The inherited parent already carries noipa on animal_path, but solve itself is unprotected.\n''')
central={'source':'User central verification in current conversation; not a local run','zip_sha256':'2f1557875d550000ae492c3814c84c78d5402e99b3a754308dc3907aa32b2178','native_sha256':'afca1d69fde38a0474546b70ecee38911477548dfde9aadc685c58a2a0b88a2f','compiler':'Ubuntu24.04 g++13.3','command':'python tests/run_checks.py --sanitize','unit_1_failure':'FAIL: positive-return maintenance lost after 25859 checks','instrumentation':'Central copied animal_collection_test.cpp outside package; inserted prints before rich assertion only; delivered production files unchanged','observed':[{'flags':'original production flags; -O3; A08_ANIMAL_COLLECTION_LABOR=1','feed':0,'value':65,'E':5,'product_0':5,'price':100,'terminal':0,'status':'FAIL'},{'flags':'-O3 replaced with -O0','feed':1,'value':65,'checks':25861,'brute_force_cases':5120,'path_cases':4608,'status':'PASS'},{'flags':'-O3 replaced with -O1 -g -fsanitize=address,undefined -fno-omit-frame-pointer','feed':1,'value':65,'status':'PASS; no reported sanitizer diagnostics'}],'new_games':0}
(r/'central_failure.json').write_text(json.dumps(central,indent=2)+'\n')
